import { AI } from "./actions"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AI>
    <html lang="en">
      <body>{children}</body>
    </html>
    </AI>
  )
}
